# Ubuntu 18.04
os: linux
dist: bionic

language: cpp

# Command(s) to install dependencies
before_install:
  - pyenv global 3.6
  - sudo apt-get update
  - sudo apt-get -y install mpic++
  - sudo apt-get -y install lcov

# Command(s) to build
install:
  - cd build
  - bash build.sh

# Command(s) to run tests and examples
script:
  - bash test.sh
  - bash example.sh

# Command(s) to calculate coverage
after_success:
  - cd coverage_report
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
